version: "3.5"

services:
 api:
  container_name: api
#   build: ./
  ports:
    - "8888:8888"
  image: golang:1.16.3-alpine
  volumes:
   - .:/go/src/api # mount current directory to the directory /go/src/api (dir in docker container)
  working_dir: /go/src/api
  command: go run src/main.go
#   links:
#     - redis
#  redis:
#    image: redis:alpine